Fix missing java error in integration-test container:
  Error: JAVA_HOME is not defined correctly.
    We cannot execute /usr/lib/jvm/java-11-openjdk/bin/java
  Exited with code 1